AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - "bin/*"
    - "pkg/**/*"
    - "vendor/**/*"

Layout/LineLength:
  Max: 80

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ParameterLists:
  Max: 5
Metrics/AbcSize:
  Max: 20
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10

Lint/RedundantRequireStatement:
  Exclude:
    - "*.gemspec"
