require_relative "../lib/stats_with_ruby/calculate_functions/mean"
require_relative "../lib/stats_with_ruby/calculate_functions/median"
require_relative "../lib/stats_with_ruby/calculate_functions/sum"
require_relative "../lib/stats_with_ruby/calculate_functions/mode"
require_relative "../lib/stats_with_ruby/calculate_functions/sqrt"
require_relative "../lib/stats_with_ruby/calculate_functions/variance"
require_relative "../lib/stats_with_ruby/calculate_functions/range"
require_relative "../lib/stats_with_ruby/calculate_functions/standard_deviation"

def calculate(data)
    puts "Data: #{data}"
    puts "Mean: #{data.mean.round(2)}"
    puts "Median: #{data.median.round(2)}"
    puts "Sum: #{data.sum.round(2)}"
    puts "Mode: #{data.mode}"
    puts "Sqrt: #{data.sqrt.round(2)}"
    puts "Variance: #{data.variance.round(2)}"
    puts "Range: #{data.range.round(2)}"
    puts "Standart deviation: #{data.standard_deviation.round(2)}"
end